version: '3.8'

# Db for development
services:
    postgres:
        hostname: postgres
        container_name: postgres
        image: postgres:14.2
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
        restart: unless-stopped
