version: '3.8'

services:
    postgres:
        hostname: postgres
        container_name: postgres
        image: postgres:14.2
        # load schema
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d
            - postgres:/var/lib/postgresql/data
        networks:
            - app
        environment:
            POSTGRES_PASSWORD: password

        restart: unless-stopped

    app:
        hostname: app
        container_name: app
        # build the image from the Dockerfile
        image: app
        networks:
            - app
        environment:
            APP_DB_HOST: postgres
            APP_DB_PORT: 5432
            APP_DB_USER: postgres
            APP_DB_PASSWORD: password
            APP_DB_DATABASE: postgres
            APP_PORT: 3000 # optional
            APP_DB_SSL: 'false' # optional
        ports:
            - '4000:3000'
        depends_on:
            - postgres

volumes:
    # postgres data
    postgres:
        name: postgres
        driver: local
        driver_opts:
            # 1gb limit
            o: 'size=1g'
            device: tmpfs
            type: tmpfs

networks:
    app:
        name: app
